### ISSUE TITLE
Medic Shops anpassen

### ISSUE THREAD

**Issue by A3Loki** [A3Loki/altislife_kommandovollrausch#12]
Skins einfügen, Preise anpassen und Items hinzufügen

**Comment by mqjulius** [comment]
cop loadout + uniformen skins angepasst (alte uniform muss noch komplett entfernt werden

**Comment by A3Loki** [comment]
-Kleidung Richtig im Shop anzeigen lassen(Dienstkleidung)
-Mehr Medic Kleidung??
-nur Kleidung und Rucksack im Dienstkleidungsladen verfügbar(keine Westen etc)
-Arztbedarfs Laden doppelt im scoll-menü(Kavala NPC)
-kaum Medic Ausrüstung und kein Essen und Trinken im Shop

**Comment by mqjulius** [comment]
gewünschte kleidung vorhanden + doppelter laden gefixt (namen fehlerhaft) + essen trinken hinzugefügt
