### ISSUE TITLE
Donatorshop

### ISSUE THREAD

**Issue by Slovakiadragon** [A3Loki/altislife_kommandovollrausch#30]
Zu Beginn nur eine Copy des Rebellenshops inkl. der Waffen und Fahrzeuge.

**Comment by jimbeam72** [comment]
es sollten schon besondere Fahrzeuge und Kleidung für den Donator verfügbar sein.
wenn auch zum Anfang von jedem nur eins inkl. Donator Skin ?
Man sollte schon einen erhöhten Anreiz zum Spenden schaffen und es besser vermarkten.
