### ISSUE TITLE
Admin Menü

### ISSUE THREAD

**Issue by Slovakiadragon** [A3Loki/altislife_kommandovollrausch#31]
Anpassen des Admin Menüs (4 Levels):

- TP der eigenen Person (ab Level 2)
- TP von Personen (ab Level 2)
- Zuschauen von Personen (ab Level 1)
- Erstattungen (finanziell) (ab Level 3)
- Einfrieren von Spielern (ab Level 3)
- God Mod (ab Level 4)
- Kicken von Personen (ab Level 2)
- Bannen von Personen (ab Level 4)

**Comment by A3Loki** [comment]
Soweit abgeschlossen, muss heute abend noch getestet werden
