### ISSUE TITLE
Ideen für Features

### ISSUE THREAD

**Issue by A3Loki** [A3Loki/altislife_kommandovollrausch#32]
V1.0:
- [x] Keine Spielernamen über den Köpfen (RP-Verbesserung)

V1.2:
- [ ] abschließbare Verwahrstelle / Gendarmerie
- [ ] Firmen (Sehr viel Aufwand, erst ab V2.0)
- [ ] Auktionshaus für Waffen, Fahrzeuge, besondere Items etc.
- [ ] Medic und Polizei Missionen (Epidemie, Bombenfund etc.)
- [ ] Polizeiverhörraum: "hinsetzen"Script einfügen

Worth to look at:
- http://www.armaholic.com/page.php?id=32083
- http://www.armaholic.com/page.php?id=26922
- http://www.armaholic.com/page.php?id=31939
- http://www.armaholic.com/page.php?id=24777
- http://www.armaholic.com/page.php?id=28425
- http://www.armaholic.com/page.php?id=30846
- http://www.armaholic.com/page.php?id=29895
- http://www.armaholic.com/page.php?id=31779
- https://www.altisliferpg.com/topic/1843-how-to-cpr-kit/
- https://www.altisliferpg.com/topic/1829-tutorial-realistic-vehicle-towing/

**Comment by A3Loki** [comment]
- https://www.altisliferpg.com/topic/1843-how-to-cpr-kit/
- https://www.altisliferpg.com/topic/1829-tutorial-realistic-vehicle-towing/

**Comment by A3Loki** [comment]
Diskothek in Kavala und Athira mit Beleuchtung und Musik.
Tuning Werkstatt (Treffpunkt für Tuner).
Bars in verschiedenen Städten.
Lokale zum Essen.
Kleine Dörfer (Wohnsiedlungen) für Gruppierungen.
Spielotheken.
Firmen (Sehr viel Aufwand, erst ab V2.0)
Auktionshaus für Waffen, Fahrzeuge, besondere Items etc.

**Comment by jimbeam72** [comment]
in Aufgaben gewandelt
