### ISSUE TITLE
Bug Day

### ISSUE THREAD

**Issue by A3Loki** [A3Loki/altislife_kommandovollrausch#33]
Nach Fertigstellung uns vorgenommener Aufgaben, würde ich Vorschlagen einen Testlauf mit mehreren Spielern zu starten.
Dies beinhaltet zurücksetzten der Spieler- und Fahrzeugdatenbank und Verteilung verschiedener Rollen (Polizei, ART, Zivis)

***Bug-Day: Verschoben!***

**Comment by MqAbdul** [comment]
26.02 maybe?

**Comment by mqjulius** [comment]
Bug Day bis auf weiteres verschoben... Vielleicht könnte man schon mal anfangen Tester mobil zu machen.
