### ISSUE TITLE
Preise anpassen

### ISSUE THREAD

**Issue by mqjulius** [A3Loki/altislife_kommandovollrausch#35]
sämtliche Preise müssen angepasst werden

**Comment by A3Loki** [comment]
Abdul, wenn du deine alten Shops suchst: b77a840c473fd94ebdd878cf534f8f408f301255

**Comment by Slovakiadragon** [comment]
Config Master: 
Shops angepasst
Lizensen angepasst

Confiq Shops:
Festpreise angepasst bei:
- Cop
- Civ
- Med

**Comment by Slovakiadragon** [comment]
Dyn. Markt angepasst
