### ISSUE TITLE
Cop Fehlerliste

### ISSUE THREAD

**Issue by jimbeam72** [A3Loki/altislife_kommandovollrausch#37]
- [x] ~Shop ist verschwunden~
- [x] ~Helishop Orca entfernen~
- [x] ~Helishop Scherrif entfernen~
- [x] ~Helishop M900 hinzufügen~
- [x] ~Interaktionsmenü Text ändern (Spieler / spieler)~
- [x] Heliport vergrössern
- [x] Möbel im Verhörraum
- [x] Beleuchtung innen und aussen
- [x] ~Fahrzeuge nach beschlagnahmen nicht in Garage ?! (Cop / B_Heli_Light_01_F)~
- [x] ~Fehlermeldung nach revive: `compatibleitem`/ is not a class (´muzzle_snds_L` accessed)~

**Comment by A3Loki** [comment]
Bei hinzufügen und entfernen von Items/Vehicles bitte direkt den Classname beischreiben

**Comment by jimbeam72** [comment]
revive error vorerst ignorieren! 
kam nach einem admin-revive über Konsole

**Comment by mqteggy** [comment]
Setz mich da morgen (24.) Mittag mal ran.
