### ISSUE TITLE
Keinen Shop beim Kavala Krankenhaus + Cop HQ

### ISSUE THREAD

**Issue by A3Loki** [A3Loki/altislife_kommandovollrausch#42]

**Comment by mqjulius** [comment]
inwiefern bei den medics? 
cop fixed

**Comment by A3Loki** [comment]
Anscheinend stand auch kein Medic Shop beim Kavala Krankenhaus meinte Rene

**Comment by jimbeam72** [comment]
Shop steht im Gebäude links vom Eingang (Raum).
Gestern abend getestet ... erl./closed
