### ISSUE TITLE
Schilder -> MAP

### ISSUE THREAD

**Issue by jimbeam72** [A3Loki/altislife_kommandovollrausch#54]
- [x] Polizeischilder einfügen
- [ ] Serverlogo (Marktplatzschild) ändern in "Willkommen ..."
- [x] Serverlogo-Schild versetzen (steht vor einem Eingang)
- [x] Shop-Schilder einfügen (ggf. muss das Format geändert werden)
- [x] Schild Donator-Straße
- [x] Schild für Markt einfügen
- [x] Schild für GunStore einfügen
- [x] Alle Grafiken auf die Schilder setzen

**Comment by mqteggy** [comment]
Lizenzen und Nahrungsmittel Schild fehlen

**Comment by jimbeam72** [comment]
Lizenzen erstelle ich
Nahrungsmittel ist die markt.jpg (costa´s Supermarkt)

**Comment by jimbeam72** [comment]
Grafiken sind soweit alle fertig und müssen auf der map eingefügt werden.
Polizei war (Stand gestern abend) noch nicht drin (deswegen Haken wieder entfernt)?!
Bei Bedarf Rücksprache mit mir halten.
GunStore und Markt haben noch keine Schilder auf der Map!

**Comment by mqjulius** [comment]
was ist das marktplatzschild?
