### ISSUE TITLE
Gewicht für Rucksäcke ändern

### ISSUE THREAD

**Issue by Slovakiadragon** [A3Loki/altislife_kommandovollrausch#55]
Ist aktuell bei 24....

**Comment by Slovakiadragon** [comment]
if(EQUAL(backback player,"B_HuntingBackpack")) then {life_maxWeight = life_maxWeight + 30}; //BP-Weight
	if(EQUAL(backback player,"B_AssaultPack_sgg")) then {life_maxWeight = life_maxWeight + 30};
	if(EQUAL(backback player,"B_Bergen_mcamo")) then {life_maxWeight = life_maxWeight + 30};
	if(EQUAL(backback player,"B_Carryall_ocamo")) then {life_maxWeight = life_maxWeight + 30};

**Comment by A3Loki** [comment]
*backpack
