### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by mqjulius** [A3Loki/altislife_kommandovollrausch#56]
- [x] Webseite inkl. Forum erstellen

**Comment by mqjulius** [comment]
https://kommandovollrausch.wixsite.com/kommandovollrausch Test 1

**Comment by jimbeam72** [comment]
Test alpha 0.1
https://vollrausch.wixsite.com/vollrausch

**Comment by jimbeam72** [comment]
Glaube wir lassen das mit Wix ...
Wir können WordPress benutzen, damit lassen sich ähnliche Ergebnisse erzielen.
Da wir eh eine Domain buchen müssen, haben wir keine Werbung auf der Seite

**Comment by A3Loki** [comment]
Ich habe bei Strato einen Webserver, müssen nur eine Domäne kaufen und darauf dann Wordpress einrichten (Das einrichten kann ich meinetwegen auch übernehmen)

**Comment by jimbeam72** [comment]
Domäne müssen wir eh kaufen: www.kommando-vollrausch.de
Oder eine Alternative wie : www.arma-kv.de
Oder neutraler: www.kv-gaming.de

**Comment by Slovakiadragon** [comment]
https://kommandovollrausch.wixsite.com/kommandovollrausch  <- BESTE !!!!

Domäne: www.kommando-vollrausch.de
