### ISSUE TITLE
Map | Schilder

### ISSUE THREAD

**Issue by jimbeam72** [A3Loki/altislife_kommandovollrausch#57]
- [x] Schild GunStore einfügen beim Waffenhändler (Zaros)
- [x] Donatorschild (Schlossallee) auf beiden seiten anbringen
- [x] Bankschild vor der Bank anbrigen
- [x] Donatorstrasse Eingang: Bunker gegen Wachhäuschen tauschen
- [x] Server Schild am Markt wurde mit Donatorstrasse belegt (Serverschild= /images/rccover.paa)
- [x] Fleischerreischild muss tiefer (wie bei Einwohnermeldeamt)
- [x] Statue am Markt in die Mitte und höher
- [x] Namen und Logos ändern/tauschen: Baumarkt in GeneralStore | Handwerkswaren in Baumarkt
- [x] Roter freier Laden in eine Bank mit Geldautomaten ändern(draussen lassen), Schild "Bank" benutzen
- [x] Fahrzeuge beim Autohändler sichtbar machen
- [x] Marktschild (Händler) einfügen: Costas Supermarkt
- [x] Schild für Einwanderungsbehörde (perso.jpg)
- [x] Schild für Orestes einfügen

**Comment by mqteggy** [comment]
was ist denn die einwanderungsbehörde??

**Comment by jimbeam72** [comment]
Der typ, bei dem man den perso bekommt?
Neben dem serverschild ... oder was hat der für eine aufgabe?

**Comment by Slovakiadragon** [comment]
Jepp, bei dem bekommt man seinen Perso

**Comment by jimbeam72** [comment]
Wie sich herausgestellt hat, bekommt man bei dem nur "Infos".
Einwaderungsbehörde kann somit bleiben (erfüllt denke ich ähnliche Aufgaben)
Perso gibt es weiterhin beim Einwohnermeldeamt

**Comment by mqteggy** [comment]
Alles klar.
Die SUVs stehen bereits und haben auch schon einen Skin?
Und im Verhörraum stehen auch schon Stühle. (Was ist mit "zum hinsetzen" gemeint?)
