### ISSUE TITLE
Schild erstellen

### ISSUE THREAD

**Issue by mqteggy** [A3Loki/altislife_kommandovollrausch#60]
- [ ] Schild für Touristen- bzw. Flüchtlingsinformationen (Orestes)

("perso.jpg"-Schild)

**Comment by jimbeam72** [comment]
??
Leon, du hast doch das perso.jpg (Einwanderungsbehörde) eingesetzt?!
Warum soll ich die grafik nun nochmals erstellen?
Das war doch für orestes

**Comment by jimbeam72** [comment]
erledigt
