### ISSUE TITLE
Wechsel auf Tanoa

### ISSUE THREAD

**Issue by mqjulius** [A3Loki/altislife_kommandovollrausch#62]
Wir sollten eventuell auf die Map Tanoa wechseln, da wir sowieso Gebäude usw. aus Tanoa benutzen ist es Leuten ohne DLC nicht möglich auf den Server zu joinen... Deshalb wäre es event. sinnvoller direkt auf Tanoa zu wechseln um das Interesse von mehr Spielern zu wecken ... Ebenfalls ist die Map RP-technisch gesehen eh sinnvoller. Scripts würden beim Wechsel gleich bleiben nur Mapping wäre ein kleiner Batzen Arbeit + Housing Script anpassen

**Comment by jimbeam72** [comment]
Diese Diskussion hatten wir doch bereits ?!
Und ich kann mich erinnern, dass bei meiner Nachfrage, warum nicht Tanoa, viele (inkl. Dir) dagegen waren.
Wir haben noch nicht einmal gestartet und wollen wieder umswitchen ?
Versteh mich nicht falsch ... ich war für Tanoa ... das würde aber wieder einiges an Arbeit bedeuten und wenn ich mir die letzten Tage anschaue, haben lediglich Loki und ich _konstant_ auf die 1.0 hingearbeitet.
Das darf als leise Kritik an ALLE verstanden werden ...

**Comment by jimbeam72** [comment]
Ich schliesse das mal, um weitere Verwirrungen zu vermeiden.
